databases:
  - name: home_app_database
    plan: free
    databaseName: home_app_database
    user: home_app_database_user

services:
  - type: web
    plan: free
    name: home-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn home.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: home_app_database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
