# Generated by Django 4.2.8 on 2023-12-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_customers_options_remove_customers_f_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
