# Generated by Django 4.2.8 on 2024-01-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_customers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/custome'),
        ),
    ]
