# Generated by Django 4.2.8 on 2023-12-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Property', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(max_length=2000)),
                ('evaluation', models.BooleanField()),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customers')),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.properties')),
            ],
        ),
    ]
