# Generated by Django 4.2.8 on 2024-01-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_message_delete_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
