# Generated by Django 4.2.8 on 2023-12-26 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Property', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('HO', 'Houses'), ('HL', 'Hole'), ('SH', 'Shop'), ('FA', 'Farme')], default='HO', max_length=2)),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customers')),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.properties')),
            ],
        ),
    ]
