# Generated by Django 4.2.8 on 2024-03-02 09:02

import Customer.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Property', '0002_properties_counter'),
        ('Images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='cid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=Customer.models.Customers),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=property)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.properties')),
            ],
        ),
    ]
