# Generated by Django 4.2.8 on 2024-03-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Images', '0002_images_cid_alter_images_image_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
