# Generated by Django 4.2.8 on 2024-03-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
