# Generated by Django 4.2.8 on 2024-03-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_properties_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='idt',
            field=models.CharField(choices=[('HO', 'Home'), ('SH', 'Shop'), ('LO', 'Loung'), ('RO', 'Room'), ('CH', 'Chaleh'), ('VI', 'Villa')], default='HO', max_length=2),
        ),
    ]
