# Generated by Django 4.2.11 on 2024-04-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0005_properties_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='ratestate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='properties',
            name='counter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
