# Generated by Django 4.2.11 on 2024-04-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0007_properties_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='counters',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='properties',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
