# Generated by Django 4.2.11 on 2024-04-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0008_properties_counters_alter_properties_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='lan',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='properties',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
    ]
